name: Manual action 
on: workflow_dispatch
jobs:
    manual_workflow: 
    runs-on: ubuntu-latest
    steps:
        - name: Manual Workflow
        run: |
          echo "Please allow this automation"
              
